@echo off
TITLE FLOWORK - FULL RESET AND FORCE REBUILD
cls
echo =================================================================
echo        FLOWORK - FULL RESET AND FORCE REBUILD
echo =================================================================
docker pull python:3.11-slim > nul
if %errorlevel% neq 0 (
    echo [ERROR] Failed to pull image 'python:3.11-slim'. Make sure Docker is connected to the internet.
    pause
    exit /b 1
)
docker run --rm -v "%~dp0:/app" python:3.11-slim python /app/generate_env.py
if %errorlevel% neq 0 (
    echo [ERROR] Failed to run generate_env.py within Docker.
    pause
    exit /b 1
)
echo [SUCCESS] The .env and docker-engine.conf files have been generated by generate_env.py.
docker info > nul 2>&1
if %errorlevel% neq 0 (
    echo [ERROR] Docker Desktop is not running. Turn it on first, then run this script again.
    pause
    exit /b 1
)
docker-compose down -v --remove-orphans
docker-compose build --no-cache
if %errorlevel% neq 0 (
    echo [ERROR]
    pause
    exit /b 1
)
echo [SUCCESS]
docker-compose up -d
echo.
docker-compose ps
echo.
echo -----------------------------------------------------------
echo [SUCCESS] All Flowork services have been started.
echo [INFO] Core Dashboard at http://localhost:5001
echo ------------------------------------------------------------
echo.
docker-compose logs --tail="50" cloudflared
echo.
echo -----------------------------------------------------------------
echo.
echo --- [ AUTO-LOG (PENTING) ] MENCARI PRIVATE KEY BARU ANDA... ---
echo.
docker compose logs gateway | findstr "LOGIN PRIVATE KEY"
echo.
echo -----------------------------------------------------------------
echo.
echo [INFO] Copy the 'LOGIN PRIVATE KEY' above and use it to login.
echo.
pause